travis:
  secure:
    BINSTAR_TOKEN: NiJNvWjOFzQywmb0U+Y/ePZG0qo+QR1ekECASc/XCezrYOIzCyRxJmANZGjpBsPfSKH6Q1RcA9GZz1D+Koc22dfgF8uH0MTRml6Gxgojq9FUn7Tn/vY0c/wxaGcalJy8gZEBCDVkhULEd+0jPlqfGZ/MmcD4WZEtC0VbeXOil/QUIyvp13kcxm8/v8cvFuinKHOFvMMi7mO1j9F2FVIvpi2WDV1ZBg8TCbrXvS59QQ4AWPbKh4/okVS4sSzoBkBEMf6bOzTD4ThGeUPsgG9Bm7NCfjscrL02AV3d9gWZK5HTnetWioXFp3tN27ahL+/p9iKJCeuE6dk/jf2YZXthEVhc+Ih1lvqFPfkNcVJRAegwXjIUGcLiw0tELF5Y8O+eWSH+Fdt/VAa+1DzG/Zt+QznANCar0wbYfBwn6ugHpiNvs8it0OPFZYUHJw0JJOKmJHJ5rfdS1LyfhvK1KjblDbyfyKHgKjV2NdmsegZtxwy3Em9nJ1nq0idZfeqKzHMtkoQZSqoa0Vdvfau7Q67qmufIox4QnBdUlylimTwNAI6cu+zNIHX1c271onQoOYvd9IMpvgcwYOgSJh8FpfkG4CO7XFomuJQTpE68pT3O6mXKpCeZb6g9hwJmPiCMdOw4xl2KMnGZk0bDm/Oq0WpzYf8o4wHg6GVoAStsaibE4H4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
