travis:
  secure:
    BINSTAR_TOKEN: lDYX1sOpGpJCrGKuLtCwhjagxCKSryE2EzbyTv5m46ouTC/c7wPUpq2Ip751XetPeJ/sJcN1/AwiDjjw5cRpn299qqVQgAe7YEMefFCI5ZHip9tFfL2hwWPOWmEfocDG+KqtCcuPPuxgEa19zFh22W+4lvRVqr1kWYl+s/ePOJd8BVvSdrj+kCndE2ryxRwz/OMcn8jug9jntLcAme5rPXwEFegZxEYXIbfQZf2yX0SdCHz+fgt8RwRy/RU7XXbE3hiPaZU+23oDBooLIcFaR7dtp55Sdhlzn6JG7gR8WYYVtzsQ770h+BQPSm8gXe6TEvPUDGf3IUJmMhA+aZFLgRqVBX3J3URrm7LGbcuus/aBjKTjmefaEdQZ2AEYlonSoM9JYzr1I0QDHn7L8xvX8Qs7vey3u1sPTHWeAXqpMieaPYGAeI3a4EjAFBGMpuhyGwUDAgtVfB9DyVfydu2zQCR26iscKhR/qUcDgJuljrYwJqtMf5B9aFXz5RbkvxDJZn78FpzC+pyoThRQwGb3SBOGeUuBQ0JyrONIswQCOKL9uiLEux/BDA6GIZF5JQ4cZ8Ec3pdMTqyPmQa8KdAwv/Hlvm09ch3V2VaDX7h480w3JKyjt50h32wDbR8/UTc+xbZ3v2Ri8uw4Bh8h5Q/WpUv7nC9t/DLQnW1c/aaSmks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
